services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - /etc/cloudflared:/etc/cloudflared
    networks:
      - public

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - public
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app

  api-gateway:
    image: node:20-alpine
    networks:
      - app
      - data

  wallet-generator:
    image: node:20-alpine
    networks:
      - app

  coin-launcher:
    image: node:20-alpine
    networks:
      - app

  postgres:
    image: postgres:16-alpine
    volumes:
      - /home/scrippa/server-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${postgres_USER}
      POSTGRES_PASSWORD: ${postgres_PASS}
      POSTGRES_DB: ${postgres_DB}
    networks:
      - data

  redis:
    image: redis
    volumes:
      - /home/scrippa/server-data/redis:/data
    networks:
      - data

networks:
  public: {}
  app: {}
  data: {}
